version: '3.7'

services:
  tacolens-backend:
    container_name: tacolens-backend
    image: tacolens-backend:1.0.0
    build:
      context: ./web-server
      dockerfile: ./Dockerfile
    ports:
      - '4567:4567'
    logging:
      options:
        max-size: '10m'
        max-file: '3'